### ISSUE TITLE
What has changed in version 5.6.3? (my package no longer works)

### ISSUE THREAD

**Issue by stla** [ericdunipace/RcppCGAL#18] opened 2024-05-02 20:03 UTC
Hello Eric,

Since version 5.6.3, the compilation of my package **cgalPolygons** throws a myriad of errors: [R CMD checks](https://github.com/stla/cgalPolygons/actions/runs/8929603563).

You can see that the check is ok on Windows, but the installation on Windows has downloaded version 5.6.2.

I'm not familiar with the compilation reports of C++ code but I'm under the impression the reports find some errors not in my code but in the CGAL code, that's very strange.

**Comment by ericdunipace** [comment] 2024-05-04 08:07
Can you try using the 5.6.1 headers from the CGAL release and see if that fixes your problem. I tried to correct another users UBSAN issue, which may be the cause, but you should test your package with the CGAL release first to see if that's the issue.

**Comment by stla** [comment] 2024-05-04 08:40
Hi,

Ok I will try later. 

I also got UBSAN issues with this package. I reported to the CGAL team and they told me these issues have been fixed.

**Comment by ericdunipace** [comment] 2024-05-07 00:54
The issues are fixed in 6.0, which should be released soon; unfortunately, when I tried building my package with the master version of the CGAL headers, it caused errors in a few of the CRAN packages. Please keep me updated.

**Comment by ericdunipace** [comment] 2024-05-07 00:55
If using the 5.6.1 version of the header files, fixes your issue, I can push a new version of the CGAL headers without my hacky UBSAN fix, probably in early June so as not to upset the CRAN mainteners. Let me know

**Comment by stla** [comment] 2024-05-15 16:41
Hello Eric,

I've tried with CGAL 5.6.1 and the R CMD checks have been successful.

**Comment by ericdunipace** [comment] 2024-07-04 22:17
Pushed a version to CRAN (5.6.4) that should fix this; I will be testing the 6.0 beta soon to see if there are any breaking changes.

**Closed by ericdunipace** 2024-07-04 22:17 UTC
